#!/usr/bin/env bash
# Installs Nginx web server with configure it.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
